server:
  port: 9527            #端口号
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
#          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
#            - After=2022-06-04T21:00:00.000+08:00[Asia/Shanghai]  #时间,必须要这个时间之后才能调用
#            - Cookie=username,xzw                                 #cookies,前面是名称,后面是正则表达式,必须匹配上才可以访问
#            - Header=xzw,\d+                                      #请求头要有xzw,并且值必须是整数
        - id: payment_route2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - Cookie=username,xzw
            - After=2022-06-04T20:50:27.274+08:00[Asia/Shanghai]
            - Header=xzw,\d+
eureka:
  instance:
    instance-id: gateway  #在服务注册中心显示的名称
    prefer-ip-address: true  #访问路径可以显示ip地址
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true  #表示会向注册中心注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka